### ISSUE TITLE
marginale druk in grafiek en legenda komen niet overeen

### ISSUE THREAD

**Issue by yurtman** [Hilbrand/ib-broncode#38]
In onderstaand voorbeeld:

https://hilbrand.github.io/ib/#/?tab=md&p=V;V,80000&w=koop;300000;7000&v=g;2024;jaar;20000,157300;100;a;200;80000

is bijvoorbeeld op 80000 inkomen de marginale druk in de grafiek boven de 60% maar volgens de legenda 38%.

Oorzaak vooralsnog onbekend, discrepantie tussen de 2 is reproduceerbaar in verschillende voorbeelden.

**Comment by Hilbrand** [comment]
Dit lijkt te maken te hebben met hoe hypotheekrente wordt meegenomen in de berekeningen. Met toevoeging van tabel, waar gegevens net iets anders worden gepresenteerd, is dit fout gegaan. In de tabel gaat het ook niet goed. Ik ga dit snel oplossen. Bedankt voor het melden.
